name: Deploy to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::919221584939:role/githubdeployemt
          aws-region: us-east-1

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
          --cluster likable-bee-kbmtqx \
          --service likable-bee-kbmtqx \
          --force-new-deployment