name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      db_name:
        description: "this is tes db"
        required: true
        default: "test_db"

      service_name:
        description: "test service_name"
        required: true
        default: "test_service"


permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: flask-app
  ECS_CLUSTER: enlightened-panda-af1gwf
  ECS_SERVICE: flask-task-service-4a61o0d9
  TASK_DEFINITION: flask-task
  CONTAINER_NAME: flask-container

jobs:
  Tests:
    runs-on: ubuntu-latest
    services:
      database:
        image: public.ecr.aws/docker/library/postgres:15.17-trixie
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: sa_password!123456
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa_password!123456
      POSTGRES_DB: flask_app_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python + deps
        uses: ./.github/actions/python-deps
        with:
          python-version: "3.11"

      - name: Prepare Postgres
        uses: ./.github/actions/postgres-prepare
        with:
          host: ${{ env.POSTGRES_HOST }}
          port: ${{ env.POSTGRES_PORT }}
          user: ${{ env.POSTGRES_USER }}
          password: ${{ env.POSTGRES_PASSWORD }}
          db: ${{ env.POSTGRES_DB }}

      - name: Run tests
        uses: ./.github/actions/run-pytest
        with:
          pytest-args: "-v"
          cov-target: "."
          cov-xml: "TestResults/coverage.xml"
          junit-xml: "TestResults/pytest-results.xml"
      
      - name: Upload test artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults
  
  Deploy:
    needs : Tests
    runs-on: ubuntu-latest
    if: ${{ success()}}
    steps:
      - name: Setup Python + deps
        uses: ./.github/actions/python-deps
        with:
          python-version: "3.11"

    
      # -------------------------
      # RUN TESTS
      # -------------------------
      - name: Run tests
        uses: ./.github/actions/run-pytest
        with:
          pytest-args: "-v"
          markers: "not integration"
          cov-target: "."
          cov-xml: ""
          junit-xml: ""
          cov-fail-under: "80"


      # -------------------------
      # CONFIGURE AWS
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::919221584939:role/githubdeployemt
          aws-region: ${{ env.AWS_REGION }}


      # -------------------------
      # LOGIN TO ECR
      # -------------------------
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # -------------------------
      # BUILD AND PUSH IMAGE
      # -------------------------
      - name: Build, tag, and push image
        id: build-image
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: ${{ env.ECR_REPOSITORY }}
          tag: ${{ github.sha }}


      # -------------------------
      # DOWNLOAD TASK DEFINITION
      # -------------------------
      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition $TASK_DEFINITION \
          --query taskDefinition > task-definition.json


      # -------------------------
      # UPDATE IMAGE
      # -------------------------
      - name: Fill new image in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}


      # -------------------------
      # DEPLOY
      # -------------------------
      - name: Deploy task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
