name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: flask-app
  ECS_CLUSTER: enlightened-panda-af1gwf
  ECS_SERVICE: flask-task-service-4a61o0d9
  TASK_DEFINITION: flask-task
  CONTAINER_NAME: flask-container

jobs:
  Tests:
    runs-on: ubuntu-latest
    services:
      database:
        image: 454115844779.dkr.ecr.us-east-1.amazonaws.com/postgres/server:17.5.172
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: sa_password!123456
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa_password!123456
      POSTGRES_DB: flask_app_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Postgres client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER"; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Create test database
        env:
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: |
          psql -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -d postgres -c "CREATE DATABASE \"$POSTGRES_DB\";" || true

      - name: Run tests
        run: |
          mkdir -p TestResults
          python -m pytest -v \
            --cov=. \
            --cov-report=xml:TestResults/coverage.xml \
            --junitxml=TestResults/pytest-results.xml
      
      - name: Upload test artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults
  
  Deploy:
    needs : Tests
    runs-on: ubuntu-latest
    if: ${{ success()}}
    steps:
      # -------------------------
      # SETUP PYTHON
      # -------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # -------------------------
      # INSTALL DEPENDENCIES
      # -------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

    
      # -------------------------
      # RUN TESTS
      # -------------------------
      - name: Run tests
        run: |
          pytest -v --cov=. --cov-fail-under=80 -m "not integration"


      # -------------------------
      # CONFIGURE AWS
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::919221584939:role/githubdeployemt
          aws-region: ${{ env.AWS_REGION }}


      # -------------------------
      # LOGIN TO ECR
      # -------------------------
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # -------------------------
      # BUILD AND PUSH IMAGE
      # -------------------------
      - name: Build, tag, and push image
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT


      # -------------------------
      # DOWNLOAD TASK DEFINITION
      # -------------------------
      - name: Download current task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition $TASK_DEFINITION \
          --query taskDefinition > task-definition.json


      # -------------------------
      # UPDATE IMAGE
      # -------------------------
      - name: Fill new image in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}


      # -------------------------
      # DEPLOY
      # -------------------------
      - name: Deploy task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
